<?php

namespace Database\Seeders;

use App\Models\MataKuliah;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MataKuliahTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $mataKuliahs = [
            ['kodemk' => 'PAIK6101', 'nama' => 'Matematika I', 'semester' => 1, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6102', 'nama' => 'Dasar Pemrograman', 'semester' => 1, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6103', 'nama' => 'Dasar Sistem', 'semester' => 1, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6104', 'nama' => 'Logika Informatika', 'semester' => 1, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6105', 'nama' => 'Struktur Diskrit', 'semester' => 1, 'sks' => 4, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'UUW00003', 'nama' => 'Pancasila dan Kewarganegaraan', 'semester' => 1, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'UUW00005', 'nama' => 'Olahraga', 'semester' => 1, 'sks' => 1, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'UUW00007', 'nama' => 'Bahasa Inggris', 'semester' => 1, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6201', 'nama' => 'Matematika II', 'semester' => 2, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6202', 'nama' => 'Algoritma dan Pemrograman', 'semester' => 2, 'sks' => 4, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6203', 'nama' => 'Organisasi dan Arsitektur Komputer', 'semester' => 2, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6204', 'nama' => 'Aljabar Linier', 'semester' => 2, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'UUW00004', 'nama' => 'Bahasa Indonesia', 'semester' => 2, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'UUW00006', 'nama' => 'Internet of Things (IoT)', 'semester' => 2, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'UUW00011', 'nama' => 'Pendidikan Agama Islam', 'semester' => 2, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'UUW00021', 'nama' => 'Pendidikan Agama Kristen', 'semester' => 2, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'UUW00031', 'nama' => 'Pendidikan Agama Katolik', 'semester' => 2, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'UUW00041', 'nama' => 'Pendidikan Agama Hindu', 'semester' => 2, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'UUW00051', 'nama' => 'Pendidikan Agama Buddha', 'semester' => 2, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'UUW00061', 'nama' => 'Pendidikan Agama Kong Hu Chu', 'semester' => 2, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'UUW00071', 'nama' => 'Aliran Kepercayaan terhadap Tuhan Yang Maha Esa', 'semester' => 2, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6301', 'nama' => 'Struktur Data', 'semester' => 3, 'sks' => 4, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6302', 'nama' => 'Sistem Operasi', 'semester' => 3, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6303', 'nama' => 'Basis Data', 'semester' => 3, 'sks' => 4, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6304', 'nama' => 'Metode Numerik', 'semester' => 3, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6305', 'nama' => 'Interaksi Manusia dan Komputer', 'semester' => 3, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6306', 'nama' => 'Statistika', 'semester' => 3, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6401', 'nama' => 'Pemrograman Berorientasi Objek', 'semester' => 4, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6402', 'nama' => 'Jaringan Komputer', 'semester' => 4, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6403', 'nama' => 'Manajemen Basis Data', 'semester' => 4, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6404', 'nama' => 'Grafika dan Komputasi Visual', 'semester' => 4, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6405', 'nama' => 'Rekayasa Perangkat Lunak', 'semester' => 4, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6406', 'nama' => 'Sistem Cerdas', 'semester' => 4, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6501', 'nama' => 'Pengembangan Berbasis Platform', 'semester' => 5, 'sks' => 4, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6502', 'nama' => 'Komputasi Tersebar dan Paralel', 'semester' => 5, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6503', 'nama' => 'Sistem Informasi', 'semester' => 5, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6504', 'nama' => 'Proyek Perangkat Lunak', 'semester' => 5, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6505', 'nama' => 'Pembelajaran Mesin', 'semester' => 5, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6506', 'nama' => 'Keamanan dan Jaminan Informasi', 'semester' => 5, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'UUW00008', 'nama' => 'Kewirausahaan', 'semester' => 5, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6601', 'nama' => 'Analisis dan Strategi Algoritma', 'semester' => 6, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6602', 'nama' => 'Uji Perangkat Lunak', 'semester' => 6, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6603', 'nama' => 'Masyarakat dan Etika Profesi', 'semester' => 6, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6604', 'nama' => 'Praktik Kerja Lapangan', 'semester' => 0, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6605', 'nama' => 'Manajemen Proyek', 'semester' => 6, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6701', 'nama' => 'Metodologi Penelitian dan Penulisan Ilmiah', 'semester' => 0, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6702', 'nama' => 'Teori Bahasa dan Otomata', 'semester' => 7, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6703', 'nama' => 'Metode Perangkat Lunak', 'semester' => 7, 'sks' => 3, 'sifat' => 'Pilihan', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6704', 'nama' => 'Kualitas Perangkat Lunak', 'semester' => 7, 'sks' => 3, 'sifat' => 'Pilihan', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6705', 'nama' => 'Pemodelan dan Simulasi', 'semester' => 7, 'sks' => 3, 'sifat' => 'Pilihan', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6706', 'nama' => 'Visi Komputer', 'semester' => 7, 'sks' => 3, 'sifat' => 'Pilihan', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6707', 'nama' => 'Audit Sistem Informasi', 'semester' => 7, 'sks' => 3, 'sifat' => 'Pilihan', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6708', 'nama' => 'Penambangan Data', 'semester' => 7, 'sks' => 3, 'sifat' => 'Pilihan', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6709', 'nama' => 'Sistem Tertanam', 'semester' => 7, 'sks' => 3, 'sifat' => 'Pilihan', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6710', 'nama' => 'Algoritma Evolusioner', 'semester' => 7, 'sks' => 3, 'sifat' => 'Pilihan', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6711', 'nama' => 'Komputasi Lunak', 'semester' => 7, 'sks' => 3, 'sifat' => 'Pilihan', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6712', 'nama' => 'Temu Balik Informasi', 'semester' => 7, 'sks' => 3, 'sifat' => 'Pilihan', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6801', 'nama' => 'Topik Khusus RPL & STI', 'semester' => 0, 'sks' => 3, 'sifat' => 'Pilihan', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6802', 'nama' => 'Topik Khusus SC & KG', 'semester' => 0, 'sks' => 3, 'sifat' => 'Pilihan', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6803', 'nama' => 'Evolusi Perangkat Lunak', 'semester' => 8, 'sks' => 3, 'sifat' => 'Pilihan', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6804', 'nama' => 'Rekayasa Sistem', 'semester' => 8, 'sks' => 3, 'sifat' => 'Pilihan', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6805', 'nama' => 'Komputasi Awan', 'semester' => 8, 'sks' => 3, 'sifat' => 'Pilihan', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6806', 'nama' => 'Arsitektur Perangkat Lunak', 'semester' => 8, 'sks' => 3, 'sifat' => 'Pilihan', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6807', 'nama' => 'Pemrograman Lanjut', 'semester' => 8, 'sks' => 3, 'sifat' => 'Pilihan', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6808', 'nama' => 'Pengenalan Pola', 'semester' => 8, 'sks' => 3, 'sifat' => 'Pilihan', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6809', 'nama' => 'Kriptografi', 'semester' => 8, 'sks' => 3, 'sifat' => 'Pilihan', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6810', 'nama' => 'Bioinformatika', 'semester' => 8, 'sks' => 3, 'sifat' => 'Pilihan', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6811', 'nama' => 'Keamanan Siber', 'semester' => 8, 'sks' => 3, 'sifat' => 'Pilihan', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6812', 'nama' => 'Pemrosesan Citra Medis', 'semester' => 8, 'sks' => 3, 'sifat' => 'Pilihan', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6813', 'nama' => 'Data Besar', 'semester' => 8, 'sks' => 3, 'sifat' => 'Pilihan', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6814', 'nama' => 'Intelijen Bisnis', 'semester' => 8, 'sks' => 3, 'sifat' => 'Pilihan', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6815', 'nama' => 'Pemodelan Informasi', 'semester' => 8, 'sks' => 3, 'sifat' => 'Pilihan', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6816', 'nama' => 'Sistem Enterprise', 'semester' => 8, 'sks' => 3, 'sifat' => 'Pilihan', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6817', 'nama' => 'Robotika', 'semester' => 8, 'sks' => 3, 'sifat' => 'Pilihan', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6818', 'nama' => 'Pengolahan Bahasa Alami', 'semester' => 8, 'sks' => 3, 'sifat' => 'Pilihan', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6819', 'nama' => 'Analisis Jaringan Sosial', 'semester' => 8, 'sks' => 3, 'sifat' => 'Pilihan', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6820', 'nama' => 'Sains Data', 'semester' => 8, 'sks' => 3, 'sifat' => 'Pilihan', 'prodi_id' => 1],
            ['kodemk' => 'PAIK6821', 'nama' => 'Tugas Akhir', 'semester' => 0, 'sks' => 6, 'sifat' => 'Wajib', 'prodi_id' => 1],
            ['kodemk' => 'UUW00009', 'nama' => 'Kuliah Kerja Nyata (KKN)', 'semester' => 0, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 1],

            //Matematika
            ['kodemk' => 'MAT101', 'nama' => 'Kalkulus I', 'semester' => 1, 'sks' => 4, 'sifat' => 'Wajib', 'prodi_id' => 2],
            ['kodemk' => 'MAT102', 'nama' => 'Aljabar Linear', 'semester' => 1, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 2],
            ['kodemk' => 'MAT103', 'nama' => 'Pengantar Matematika', 'semester' => 1, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 2],
            ['kodemk' => 'MAT201', 'nama' => 'Kalkulus II', 'semester' => 2, 'sks' => 4, 'sifat' => 'Wajib', 'prodi_id' => 2],
            ['kodemk' => 'MAT202', 'nama' => 'Struktur Aljabar', 'semester' => 2, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 2],
            ['kodemk' => 'MAT203', 'nama' => 'Matematika Diskrit', 'semester' => 2, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 2],
            ['kodemk' => 'MAT301', 'nama' => 'Kalkulus III', 'semester' => 3, 'sks' => 4, 'sifat' => 'Wajib', 'prodi_id' => 2],
            ['kodemk' => 'MAT302', 'nama' => 'Analisis Real', 'semester' => 3, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 2],
            ['kodemk' => 'MAT303', 'nama' => 'Teori Bilangan', 'semester' => 3, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 2],
            ['kodemk' => 'MAT401', 'nama' => 'Analisis Kompleks', 'semester' => 4, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 2],
            ['kodemk' => 'MAT402', 'nama' => 'Persamaan Diferensial', 'semester' => 4, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 2],
            ['kodemk' => 'MAT403', 'nama' => 'Statistika Matematika', 'semester' => 4, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 2],
            ['kodemk' => 'MAT501', 'nama' => 'Metode Numerik', 'semester' => 5, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 2],
            ['kodemk' => 'MAT502', 'nama' => 'Topologi', 'semester' => 5, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 2],
            ['kodemk' => 'MAT503', 'nama' => 'Pemodelan Matematika', 'semester' => 5, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 2],
            ['kodemk' => 'MAT601', 'nama' => 'Analisis Fungsional', 'semester' => 6, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 2],
            ['kodemk' => 'MAT602', 'nama' => 'Teori Ukuran dan Integral', 'semester' => 6, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 2],
            ['kodemk' => 'MAT603', 'nama' => 'Matematika Keuangan', 'semester' => 6, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 2],
            ['kodemk' => 'MAT701', 'nama' => 'Seminar Matematika', 'semester' => 7, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 2],
            ['kodemk' => 'MAT702', 'nama' => 'Etika Profesi', 'semester' => 7, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 2],
            ['kodemk' => 'MAT703', 'nama' => 'Magang', 'semester' => 7, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 2],
            ['kodemk' => 'MAT801', 'nama' => 'Tugas Akhir', 'semester' => 8, 'sks' => 6, 'sifat' => 'Wajib', 'prodi_id' => 2],
            ['kodemk' => 'MAT802', 'nama' => 'Matematika Terapan', 'semester' => 8, 'sks' => 3, 'sifat' => 'Pilihan', 'prodi_id' => 2],
            ['kodemk' => 'MAT803', 'nama' => 'Matematika Murni', 'semester' => 8, 'sks' => 3, 'sifat' => 'Pilihan', 'prodi_id' => 2],

            //Statistika
            ['kodemk' => 'MPK201', 'nama' => 'Pendidikan Agama', 'semester' => 1, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 3],
            ['kodemk' => 'MBB206', 'nama' => 'Ilmu Sosial Budaya Dasar', 'semester' => 1, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 3],
            ['kodemk' => 'PAS203', 'nama' => 'Kalkulus I', 'semester' => 1, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 3],
            ['kodemk' => 'MPK202', 'nama' => 'Pancasila dan Kewarganegaraan', 'semester' => 2, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 3],
            ['kodemk' => 'PAS208P', 'nama' => 'Algoritma dan Pemrograman', 'semester' => 2, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 3],
            ['kodemk' => 'PAS210P', 'nama' => 'Analisis Data Eksploratif', 'semester' => 2, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 3],
            ['kodemk' => 'MPK205', 'nama' => 'Bahasa Indonesia', 'semester' => 3, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 3],
            ['kodemk' => 'PAS403', 'nama' => 'Kalkulus III', 'semester' => 3, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 3],
            ['kodemk' => 'PAS213P', 'nama' => 'Metode Numerik', 'semester' => 3, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 3],
            ['kodemk' => 'PAS217', 'nama' => 'Metodologi Penelitian', 'semester' => 4, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 3],
            ['kodemk' => 'PAS308P', 'nama' => 'Komputasi Statistika', 'semester' => 4, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 3],
            ['kodemk' => 'PAS409', 'nama' => 'Statistika Matematika II', 'semester' => 4, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 3],
            ['kodemk' => 'PAS230', 'nama' => 'Matematika Finansial', 'semester' => 5, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 3],
            ['kodemk' => 'PAS231P', 'nama' => 'Analisis Data Kategori', 'semester' => 5, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 3],
            ['kodemk' => 'PAS232P', 'nama' => 'Analisis Runtun Waktu', 'semester' => 5, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 3],
            ['kodemk' => 'MWU209', 'nama' => 'Kewirausahaan', 'semester' => 6, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 3],
            ['kodemk' => 'PAS243P', 'nama' => 'Teknik Simulasi', 'semester' => 6, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 3],
            ['kodemk' => 'PAS342', 'nama' => 'Praktek Kerja Lapangan', 'semester' => 7, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 3],
            ['kodemk' => 'MWU211', 'nama' => 'Kuliah Kerja Nyata', 'semester' => 7, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 3],
            ['kodemk' => 'PAS250', 'nama' => 'MK Pilihan 22: Standardisasi', 'semester' => 7, 'sks' => 3, 'sifat' => 'Pilihan', 'prodi_id' => 3],
            ['kodemk' => 'PAS349', 'nama' => 'Tugas Akhir', 'semester' => 8, 'sks' => 4, 'sifat' => 'Wajib', 'prodi_id' => 3],
            ['kodemk' => 'PAS253P', 'nama' => 'MK Pilihan 26: Metode Wavelet', 'semester' => 8, 'sks' => 3, 'sifat' => 'Pilihan', 'prodi_id' => 3],
            ['kodemk' => 'PAS328', 'nama' => 'MK Pilihan 27: Asuransi Lanjut', 'semester' => 8, 'sks' => 3, 'sifat' => 'Pilihan', 'prodi_id' => 3],

            //Kimia
            ['kodemk' => 'KIM101', 'nama' => 'Kimia Dasar I', 'semester' => 1, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 4],
            ['kodemk' => 'KIM102', 'nama' => 'Praktikum Kimia Dasar I', 'semester' => 1, 'sks' => 1, 'sifat' => 'Wajib', 'prodi_id' => 4],
            ['kodemk' => 'KIM103', 'nama' => 'Matematika Dasar', 'semester' => 1, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 4],
            ['kodemk' => 'KIM201', 'nama' => 'Kimia Dasar II', 'semester' => 2, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 4],
            ['kodemk' => 'KIM202', 'nama' => 'Praktikum Kimia Dasar II', 'semester' => 2, 'sks' => 1, 'sifat' => 'Wajib', 'prodi_id' => 4],
            ['kodemk' => 'KIM203', 'nama' => 'Fisika Dasar', 'semester' => 2, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 4],
            ['kodemk' => 'KIM301', 'nama' => 'Kimia Organik I', 'semester' => 3, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 4],
            ['kodemk' => 'KIM302', 'nama' => 'Kimia Anorganik I', 'semester' => 3, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 4],
            ['kodemk' => 'KIM303', 'nama' => 'Kimia Fisika I', 'semester' => 3, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 4],
            ['kodemk' => 'KIM401', 'nama' => 'Kimia Organik II', 'semester' => 4, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 4],
            ['kodemk' => 'KIM402', 'nama' => 'Kimia Anorganik II', 'semester' => 4, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 4],
            ['kodemk' => 'KIM403', 'nama' => 'Kimia Fisika II', 'semester' => 4, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 4],
            ['kodemk' => 'KIM501', 'nama' => 'Biokimia', 'semester' => 5, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 4],
            ['kodemk' => 'KIM502', 'nama' => 'Kimia Analitik I', 'semester' => 5, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 4],
            ['kodemk' => 'KIM503', 'nama' => 'Spektroskopi Molekul', 'semester' => 5, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 4],
            ['kodemk' => 'KIM601', 'nama' => 'Kimia Analitik II', 'semester' => 6, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 4],
            ['kodemk' => 'KIM602', 'nama' => 'Kimia Material', 'semester' => 6, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 4],
            ['kodemk' => 'KIM603', 'nama' => 'Metodologi Penelitian', 'semester' => 6, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 4],
            ['kodemk' => 'KIM701', 'nama' => 'Seminar Kimia', 'semester' => 7, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 4],
            ['kodemk' => 'KIM702', 'nama' => 'Etika Profesi', 'semester' => 7, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 4],
            ['kodemk' => 'KIM703', 'nama' => 'Magang', 'semester' => 7, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 4],
            ['kodemk' => 'KIM801', 'nama' => 'Tugas Akhir', 'semester' => 8, 'sks' => 6, 'sifat' => 'Wajib', 'prodi_id' => 4],
            ['kodemk' => 'KIM802', 'nama' => 'Kimia Terapan', 'semester' => 8, 'sks' => 3, 'sifat' => 'Pilihan', 'prodi_id' => 4],
            ['kodemk' => 'KIM803', 'nama' => 'Kimia Lingkungan', 'semester' => 8, 'sks' => 3, 'sifat' => 'Pilihan', 'prodi_id' => 4],

            //Fisika
            ['kodemk' => 'PAFS6311', 'nama' => 'Fisika Dasar I', 'semester' => 1, 'sks' => 4, 'sifat' => 'Wajib', 'prodi_id' => 5],
            ['kodemk' => 'PAFS6312', 'nama' => 'Praktikum Fisika Dasar', 'semester' => 1, 'sks' => 1, 'sifat' => 'Wajib', 'prodi_id' => 5],
            ['kodemk' => 'PAFS6313', 'nama' => 'Kalkulus dan Vektor', 'semester' => 1, 'sks' => 4, 'sifat' => 'Wajib', 'prodi_id' => 5],
            ['kodemk' => 'PAFS6316', 'nama' => 'Metode Pengukuran Fisis', 'semester' => 1, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 5],
            ['kodemk' => 'UUW000X1', 'nama' => 'Pendidikan Agama', 'semester' => 1, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 5],
            ['kodemk' => 'UUW00013', 'nama' => 'Pancasila dan Kewarganegaraan', 'semester' => 1, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 5],
            ['kodemk' => 'UUW00054', 'nama' => 'Bahasa Indonesia', 'semester' => 1, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 5],
            ['kodemk' => 'UUW00055', 'nama' => 'Olahraga', 'semester' => 1, 'sks' => 1, 'sifat' => 'Wajib', 'prodi_id' => 5],
            ['kodemk' => 'UUW00057', 'nama' => 'Bahasa Inggris', 'semester' => 1, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 5],
            ['kodemk' => 'PAFS6321', 'nama' => 'Fisika Dasar II', 'semester' => 2, 'sks' => 4, 'sifat' => 'Wajib', 'prodi_id' => 5],
            ['kodemk' => 'PAFS6322', 'nama' => 'Praktikum Fisika Dasar II', 'semester' => 2, 'sks' => 1, 'sifat' => 'Wajib', 'prodi_id' => 5],
            ['kodemk' => 'PAFS6323', 'nama' => 'Fisika Matematika I', 'semester' => 2, 'sks' => 4, 'sifat' => 'Wajib', 'prodi_id' => 5],
            ['kodemk' => 'PAFS6324', 'nama' => 'Termodinamika', 'semester' => 2, 'sks' => 4, 'sifat' => 'Wajib', 'prodi_id' => 5],
            ['kodemk' => 'PAFS6325', 'nama' => 'Gelombang', 'semester' => 2, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 5],
            ['kodemk' => 'PAFS6317', 'nama' => 'Biologi', 'semester' => 2, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 5],
            ['kodemk' => 'PAFS6314', 'nama' => 'Kimia', 'semester' => 2, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 5],
            ['kodemk' => 'PAFS6315', 'nama' => 'Praktikum Kimia Dasar', 'semester' => 2, 'sks' => 1, 'sifat' => 'Wajib', 'prodi_id' => 5],
            ['kodemk' => 'UUW00056', 'nama' => 'Internet of Things', 'semester' => 2, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 5],
            ['kodemk' => 'PAFS6331', 'nama' => 'Elektronika Dasar', 'semester' => 3, 'sks' => 4, 'sifat' => 'Wajib', 'prodi_id' => 5],
            ['kodemk' => 'PAFS6332', 'nama' => 'Praktikum Elektronika Dasar', 'semester' => 3, 'sks' => 1, 'sifat' => 'Wajib', 'prodi_id' => 5],
            ['kodemk' => 'PAFS6333', 'nama' => 'Elektromagnetika', 'semester' => 3, 'sks' => 4, 'sifat' => 'Wajib', 'prodi_id' => 5],
            ['kodemk' => 'PAFS6334', 'nama' => 'Fisika Matematika II', 'semester' => 3, 'sks' => 4, 'sifat' => 'Wajib', 'prodi_id' => 5],
            ['kodemk' => 'PAFS6335', 'nama' => 'Fisika Modern', 'semester' => 3, 'sks' => 4, 'sifat' => 'Wajib', 'prodi_id' => 5],
            ['kodemk' => 'PAFS6336', 'nama' => 'Praktikum Fisika Modern', 'semester' => 3, 'sks' => 1, 'sifat' => 'Wajib', 'prodi_id' => 5],
            ['kodemk' => 'PAFS6337', 'nama' => 'Mekanika', 'semester' => 3, 'sks' => 4, 'sifat' => 'Wajib', 'prodi_id' => 5],
            ['kodemk' => 'PAFS6341', 'nama' => 'Fisika Statistik', 'semester' => 4, 'sks' => 4, 'sifat' => 'Wajib', 'prodi_id' => 5],
            ['kodemk' => 'PAFS6342', 'nama' => 'Fisika Matematika III', 'semester' => 4, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 5],
            ['kodemk' => 'PAFS6343', 'nama' => 'Instrumentasi', 'semester' => 4, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 5],
            ['kodemk' => 'PAFS6344', 'nama' => 'Optika Modern', 'semester' => 4, 'sks' => 4, 'sifat' => 'Wajib', 'prodi_id' => 5],
            ['kodemk' => 'PAFS6345', 'nama' => 'Fisika Kuantum', 'semester' => 4, 'sks' => 4, 'sifat' => 'Wajib', 'prodi_id' => 5],
            ['kodemk' => 'PAFS6346', 'nama' => 'Fisika Komputasi', 'semester' => 4, 'sks' => 4, 'sifat' => 'Wajib', 'prodi_id' => 5],
            ['kodemk' => 'PAFS6347', 'nama' => 'Praktikum Fisika Komputasi', 'semester' => 4, 'sks' => 1, 'sifat' => 'Wajib', 'prodi_id' => 5],
            ['kodemk' => 'PAFS6351', 'nama' => 'Metodologi Penelitian', 'semester' => 5, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 5],
            ['kodemk' => 'PAFS6352', 'nama' => 'Simulasi dan Pemodelan', 'semester' => 5, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 5],
            ['kodemk' => 'PAFS6353', 'nama' => 'Fisika Zat Padat', 'semester' => 5, 'sks' => 4, 'sifat' => 'Wajib', 'prodi_id' => 5],
            ['kodemk' => 'PAFS6354', 'nama' => 'Fisika Nuklir', 'semester' => 5, 'sks' => 4, 'sifat' => 'Wajib', 'prodi_id' => 5],
            ['kodemk' => 'PAFS6355', 'nama' => 'Standarisasi', 'semester' => 5, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 5],
            ['kodemk' => 'PAFS6356', 'nama' => 'Sinyal dan Sistem', 'semester' => 5, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 5],
            ['kodemk' => 'PAFS6357', 'nama' => 'Praktek Kerja Laboratorium', 'semester' => 5, 'sks' => 1, 'sifat' => 'Wajib', 'prodi_id' => 5],
            ['kodemk' => 'PAFS6361', 'nama' => 'Metode Pengolahan Data', 'semester' => 5, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 5],
            ['kodemk' => 'UUW00058', 'nama' => 'Kewirausahaan', 'semester' => 5, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 5],

            //Biologi
            ['kodemk' => 'UUW00044', 'nama' => 'Kewarganegaraan', 'semester' => 1, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'PABL6101', 'nama' => 'Pengantar Biodiversitas', 'semester' => 1, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'UUW00045', 'nama' => 'Olahraga', 'semester' => 1, 'sks' => 1, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'UUW00046', 'nama' => 'Internet of Things (IoT)', 'semester' => 1, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'PABL6102', 'nama' => 'Biologi Dasar 1', 'semester' => 1, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'PABL6103', 'nama' => 'Morfologi Tumbuhan', 'semester' => 1, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'PABL6104', 'nama' => 'Anatomi Hewan', 'semester' => 1, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'PABL6105', 'nama' => 'Biologi Sel', 'semester' => 1, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'PABL6106', 'nama' => 'Kimia Dasar', 'semester' => 1, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'UUW00145', 'nama' => 'Bahasa Indonesia', 'semester' => 2, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'UUW00047', 'nama' => 'Bahasa Inggris', 'semester' => 2, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'PABL6201', 'nama' => 'Taksonomi', 'semester' => 2, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'UUW00611', 'nama' => 'Agama', 'semester' => 2, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'LABL6202', 'nama' => 'Anatomi Tumbuhan', 'semester' => 2, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'PABL6203', 'nama' => 'Biologi Dasar 2', 'semester' => 2, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'LABL6204', 'nama' => 'Biokimia', 'semester' => 2, 'sks' => 4, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'PABL6205', 'nama' => 'Embriologi Hewan', 'semester' => 2, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'PABL6301', 'nama' => 'Metodologi Penelitian', 'semester' => 3, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'LABL6302', 'nama' => 'Fisiologi Tumbuhan', 'semester' => 3, 'sks' => 4, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'LABL6303', 'nama' => 'Fisiologi Hewan', 'semester' => 3, 'sks' => 4, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'LABL6304', 'nama' => 'Mikrobiologi', 'semester' => 3, 'sks' => 4, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'PABL6305', 'nama' => 'Pengantar Biokonservasi', 'semester' => 3, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'PABL6306', 'nama' => 'Biodiversitas Tumbuhan', 'semester' => 3, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'PABL6307', 'nama' => 'Ekologi', 'semester' => 3, 'sks' => 4, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'PABL6401', 'nama' => 'Genetika', 'semester' => 4, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'PABL6402', 'nama' => 'Ilmu Lingkungan', 'semester' => 4, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'PABL6403', 'nama' => 'Biostatistika', 'semester' => 4, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'PABL6404', 'nama' => 'Biologi Molekuler', 'semester' => 4, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'PABL6405', 'nama' => 'Biologi Protista', 'semester' => 4, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'LABL6406', 'nama' => 'Biodiversitas Hewan', 'semester' => 4, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'LABL6407', 'nama' => 'Mikroteknik Tumbuhan', 'semester' => 4, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'LABL6408', 'nama' => 'Histologi', 'semester' => 4, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'PABL6409', 'nama' => 'Biologi Jamur', 'semester' => 4, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'PABL6501', 'nama' => 'Teknik Komunikasi Ilmiah', 'semester' => 5, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'PABL6502', 'nama' => 'Embriologi Tumbuhan', 'semester' => 5, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'PABL6503', 'nama' => 'Mikroteknik Hewan', 'semester' => 5, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'PABL6504', 'nama' => 'Biosistematika', 'semester' => 5, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'PABL6505', 'nama' => 'Genetika Rekombinan', 'semester' => 5, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'PABL6506', 'nama' => 'Biokonservasi', 'semester' => 5, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'PABL6507', 'nama' => 'Biofisika', 'semester' => 5, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'PABL6508', 'nama' => 'Kerja Praktek', 'semester' => 5, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'LABL6509', 'nama' => 'Dasar-Dasar Bioteknologi', 'semester' => 5, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'UUW00048', 'nama' => 'Kewirausahaan', 'semester' => 6, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'UUW00069', 'nama' => 'KKN', 'semester' => 6, 'sks' => 3, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'PABL6601', 'nama' => 'Sumber Daya Genetik', 'semester' => 6, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'PABL6602', 'nama' => 'Bioinformatika', 'semester' => 6, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'PABL6603', 'nama' => 'Biologi Laut', 'semester' => 6, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'PABL6701', 'nama' => 'Evolusi', 'semester' => 7, 'sks' => 2, 'sifat' => 'Wajib', 'prodi_id' => 6],
            ['kodemk' => 'PABL6801', 'nama' => 'Tugas Akhir', 'semester' => 8, 'sks' => 6, 'sifat' => 'Wajib', 'prodi_id' => 6],
        ];

        foreach($mataKuliahs as $mataKuliah){
            MataKuliah::create($mataKuliah);
        }
    }
}
